# Generated by Django 3.1.7 on 2021-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210522_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='km',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
