# Generated by Django 3.1.7 on 2021-05-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210526_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='km',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
