# Generated by Django 3.1.7 on 2021-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210526_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.CharField(choices=[('Banner', 'Banner'), ('Banner1', 'Banner1'), ('Banner2', 'Banner2'), ('Banner3', 'Banner3')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
