# Generated by Django 3.1.7 on 2021-05-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210526_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
    ]
