# Generated by Django 3.1.7 on 2021-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gear',
            field=models.CharField(choices=[('Otomatil', 'Otomatik'), ('Manuel', 'Manuel')], max_length=10),
        ),
    ]
