# Generated by Django 3.1.7 on 2021-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210618_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gear',
            field=models.CharField(choices=[('Otomatik', 'Otomatik'), ('Manuel', 'Manuel')], max_length=10),
        ),
    ]
