# Generated by Django 3.1.7 on 2021-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
    ]
