# Generated by Django 3.1.7 on 2021-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210525_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rentday',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
