# Generated by Django 3.1.7 on 2021-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_rentday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rentday',
        ),
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
