# Generated by Django 3.1.7 on 2021-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20210525_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
