# Generated by Django 3.1.7 on 2021-05-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20210525_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rezdate',
        ),
    ]
