# Generated by Django 3.1.7 on 2021-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_reservation_rezdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rezdate1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
