# Generated by Django 3.1.7 on 2021-05-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_reservation_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rate',
        ),
    ]
