# Generated by Django 3.1.7 on 2021-05-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_reservation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='days',
        ),
    ]
