# Generated by Django 3.1.7 on 2021-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_remove_reservation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
