# Generated by Django 3.1.7 on 2021-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_reservation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returnplace',
            field=models.CharField(choices=[('İstanbul"', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir')], default='İstanbul', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rezplace',
            field=models.CharField(choices=[('İstanbul"', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir')], default='İstanbul', max_length=20),
        ),
    ]
