# Generated by Django 3.1.7 on 2021-05-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_auto_20210527_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='returnplace',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rezplace',
        ),
    ]
