# Generated by Django 3.1.7 on 2021-05-31 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_auto_20210527_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 31, 14, 25, 48, 561062, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
