# Generated by Django 3.1.7 on 2021-05-31 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0029_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 31, 15, 2, 2, 727431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
