# Generated by Django 3.1.7 on 2021-05-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_reservation_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='returndate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rezdate',
        ),
    ]
