# Generated by Django 3.1.7 on 2021-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0031_auto_20210531_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='return_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='returndate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='rezdate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
