# Generated by Django 3.1.7 on 2021-05-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_reservation_return_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='return_reservation_date',
            new_name='reservation_backdate',
        ),
    ]
