# Generated by Django 3.1.7 on 2021-05-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0034_auto_20210531_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_backdate',
        ),
    ]
