# Generated by Django 3.1.7 on 2021-06-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0035_remove_reservation_reservation_backdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
    ]
