# Generated by Django 3.1.7 on 2021-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0036_remove_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returnplace',
            field=models.CharField(choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir')], default='İstanbul', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rezplace',
            field=models.CharField(choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir')], default='Ankara', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='returndate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='returntime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rezdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reztime',
            field=models.TimeField(),
        ),
    ]
