# Generated by Django 3.1.7 on 2021-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0038_auto_20210605_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
