# Generated by Django 3.1.7 on 2021-06-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0039_reservation_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='price',
            new_name='total',
        ),
    ]
