# Generated by Django 3.1.7 on 2021-06-18 01:02

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0040_auto_20210618_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=10, verbose_name=product.models.Product),
            preserve_default=False,
        ),
    ]
