# Generated by Django 3.1.7 on 2021-06-18 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0042_remove_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 52, 41, 882037, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='stop_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 52, 49, 635823, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
