# Generated by Django 3.1.7 on 2021-06-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0043_auto_20210618_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='stop_time',
        ),
    ]
