# Generated by Django 3.1.7 on 2021-06-18 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0044_auto_20210618_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 11, 30, 19, 918780, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='stopdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 11, 30, 25, 125274, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
