# Generated by Django 3.1.7 on 2021-06-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0045_auto_20210618_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='returndate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='returntime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rezdate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reztime',
        ),
    ]
