# Generated by Django 3.1.7 on 2021-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0046_auto_20210618_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationdate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='stopdate',
        ),
        migrations.AddField(
            model_name='reservation',
            name='returndate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='returntime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='rezdate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reztime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
