# Generated by Django 3.1.7 on 2021-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0050_remove_reservation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
