# Generated by Django 3.1.7 on 2021-06-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0057_reservation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='days',
        ),
    ]
