# Generated by Django 3.1.7 on 2021-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0058_remove_reservation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('OnStandBy', 'Beklemede'), ('Approved', 'Onaylanı'), ('Denied', 'Reddedildi')], default='New', max_length=10),
        ),
    ]
