# Generated by Django 3.1.7 on 2021-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0059_auto_20210618_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='New', max_length=10),
        ),
    ]
