# Generated by Django 3.1.7 on 2021-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0060_auto_20210618_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
