# Generated by Django 3.1.7 on 2021-06-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0061_auto_20210619_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='days',
        ),
    ]
